# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shawerma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
    ]
