# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shawerma', '0002_remove_order_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderditem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='shawerma.MenuItem'),
        ),
        migrations.AlterField(
            model_name='orderditem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='shawerma.Order'),
        ),
    ]
